---
title: "Public/Private Share for `r params$country`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
    highlight: kate
  officedown::rdocx_document:
    reference_docx: report-template.docx
  pdf_document:
    toc: false
    latex_engine: lualatex
params:
  cache: NULL
  i18n: NULL

  adminlevel_1: NULL
  country: NULL
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = TRUE,
  fig.width=7, 
  fig.height=5, 
  dpi=1200
)

library(cd2030.core)
library(dplyr)
library(purrr)
library(reactable)
library(officedown)
library(officer)

cache <- params$cache
i18n <- params$i18n
```

## National Ownership of Health Facilities

```{r}
  cache$generate_private_sector_data(
    legend_labels = list(
      Private = i18n$t("lbl_private"),
      NGO     = i18n$t("lbl_ngo"),
      Public  = i18n$t("lbl_public")
    )) %>% 
    plot(
      title  = i18n$t("title_private_sector_graph"),
      x_axis = i18n$t("xlab_private_sector"),
      y_axis = i18n$t("ylab_private_sector")
    ) + cd_report_theme()
```

## National Private Share of Services

```{r}
  cache$national_private_share %>% 
    plot(i18n = i18n) + cd_report_theme()
```

## Sub-National Private Share of Services by Area

```{r}
  cache$area_private_share %>% 
    plot(i18n = i18n) + cd_report_theme()
```
