# Column names used unquoted in dplyr/tidyr/ggplot2 code (and a few reactive arguments), declared so R CMD check
# does not report them as undefined globals.
utils::globalVariables(c(
  ".", ".value_round", "0.025", "0.975", "Data Quality Metrics", "Demand Satisfied with a Modern Method (%)", "Marital status", "N",
  "NAME_1", "Percentile", "Prevalence of Modern Methods (mCPR) (%)", "Public", "Year", "admin1_pop", "admin1_survey_change", "admin1_survey_pop",
  "admin_data", "admin_level_1", "adminlevel_1", "allbirths_dhis2", "anc1", "anc4", "anc_1trimester", "area",
  "bcg", "benchmark_flag", "category", "change", "ciratio", "color_category", "countdownmean", "country",
  "countryname", "cov_measles1_wuenic", "cov_measles2_wuenic", "cov_penta1_wuenic", "cov_penta3_wuenic", "coverage_type", "coverage_value", "csection",
  "curative_services_index", "dat", "data", "district", "envelope_pop", "facility", "facility_type", "gap_facility_minus_survey",
  "header", "hiv_test", "ideliv", "ifa90", "indic", "indic_label", "indicator", "indicator_label",
  "indicator_name", "indiclabel", "instlivebirths", "ipd_rr", "ipd_total", "ipd_under5", "ipt2", "ipt3",
  "ipv1", "ipv2", "is_outlier", "iso", "iso3", "isocode", "label", "label_lookup",
  "level", "line_type", "line_type_id", "live_births", "low_bweight", "low_opd_rr", "lower", "lower_bound",
  "maternal_deaths", "mch_prev_services_index", "mean_out_all", "mean_rr", "measles1", "measles2", "med_val", "method",
  "method_lbl", "metric", "mis_ipd_under5", "mis_opd_under5", "mmr_inst", "mmr_low", "name", "nat_pop",
  "nat_survey_change", "nat_survey_pop", "neonatal_deaths", "ngo_facility_share", "nn_inst", "no", "num_csection", "on_conflict",
  "opd_rr", "opd_total", "opd_under5", "opd_under5_outlier5std", "opv1", "opv2", "opv3", "outlier_flag",
  "pcv1", "pcv2", "pcv3", "penta1", "penta2", "penta3", "perc_diff", "perc_ipd_under5",
  "perc_opd_under5", "pnc48h", "pop", "privateShare", "private_facility_share", "r", "r_raw", "r_raw_Private",
  "r_raw_Public", "rat", "ratio_bed_pop", "ratio_fac_pop", "ratio_hstaff_pop", "ratio_ipd_pop", "ratio_md_sb", "ratio_opd_pop",
  "ratio_opd_u5_ipd_u5", "raw_metric", "raw_month", "rota1", "rota2", "routine_value", "sba", "sbr_inst",
  "sbr_low", "score_infrastructure", "score_total", "score_utilization", "score_workforce", "se", "se_raw", "section",
  "sector", "series", "series_label", "service_coverage", "share", "share_csection", "short_id", "short_indicator",
  "stillbirth_f", "suffix", "survey", "syphilis_test", "totalPrevalence", "total_beds", "total_births", "total_csection",
  "total_deaths", "total_facilities", "total_healthstaff", "total_hospitals", "total_ipd", "total_ipd_u5", "total_nonclinique_phys", "total_nonprofit",
  "total_nursemidwife", "total_nurses", "total_opd", "total_opd_u5", "total_physicians", "total_pop", "total_pop_u5", "total_prevalence",
  "total_profit", "total_stillbirth", "totbirths_anc1", "totbirths_dhis2", "totbirths_penta1", "totdeliv_anc1", "totdeliv_dhis2", "totdeliv_penta1",
  "totdeliv_un", "totinftmeasles_anc1", "totinftmeasles_dhis2", "totinftmeasles_penta1", "totinftmeasles_un", "totinftpenta_anc1", "totinftpenta_anc1derived", "totinftpenta_dhis2",
  "totinftpenta_penta1", "totinftpenta_penta1derived", "totinftpenta_un", "totlbirths_anc1", "totlbirths_penta1", "totlivebirths_dhis2", "totpreg_anc1", "totpreg_dhis2",
  "totpreg_penta1", "totpreg_un", "totunder1_dhis2", "type", "ul", "un_births", "un_under1y", "under1_dhis2",
  "under1_pop", "under5_deaths", "under5_pop", "unicefregion", "upper", "upper_bound", "use_admin1", "val",
  "value", "values", "with", "x_val", "xintercept", "y2020", "y2024", "y_pos_text",
  "year_diff", "year_left", "year_right"
))
